import type {
  Project,
  Experience,
  SkillCategory,
  Service,
  NavLink,
} from "@/types";

export const NAV_LINKS: NavLink[] = [
  { label: "Home", target: "home" },
  { label: "About", target: "about" },
  { label: "Skills", target: "skills" },
  { label: "Projects", target: "projects" },
  { label: "Experience", target: "experience" },
  { label: "Contact", target: "contact" },
];

export const CV_URL =
  "https://drive.google.com/uc?export=download&id=1QWdgp1gEF2cJdt4slakH0SUCJDvJRjcG";
export const EMAIL = "duongnguyenqn1323@gmail.com";

export const SKILLS: SkillCategory[] = [
  {
    category: "Frontend",
    icon: "Atom",
    color: "from-cyan-500 to-blue-500",
    skills: [
      { name: "ReactJS", level: 90 },
      { name: "NextJS", level: 85 },
      { name: "React Native", level: 80 },
      { name: "TailwindCSS", level: 95 },
      { name: "Redux", level: 85 },
      { name: "Bootstrap", level: 90 },
      { name: "TypeScript", level: 80 },
      { name: "JQuery", level: 95 },
      { name: "Shadcn UI", level: 85 },
    ],
  },
  {
    category: "Backend",
    icon: "Cpu",
    color: "from-orange-500 to-red-600",
    skills: [
      { name: "Java", level: 90 },
      { name: "Spring Boot", level: 92 },
      { name: "REST API", level: 95 },
    ],
  },
  {
    category: "Tools",
    icon: "Workflow",
    color: "from-indigo-500 to-purple-600",
    skills: [
      { name: "VS code", level: 85 },
      { name: "Antigravity", level: 80 },
      { name: "Bruno", level: 90 },
      { name: "GitHub/GitLab", level: 95 },
      { name: "Postman", level: 90 },
      { name: "Jira", level: 90 },
      { name: "IntelliJ IDEA", level: 95 },
    ],
  },
  {
    category: "DevOps",
    icon: "Boxes",
    color: "from-blue-600 to-cyan-600",
    skills: [
      { name: "Docker", level: 85 },
      { name: "AWS (EC2, S3, Cognito)", level: 80 },
      { name: "Jenkins", level: 85 },
      { name: "Nginx", level: 90 },
      { name: "Render", level: 85 },
      { name: "Vercel", level: 80 },
    ],
  },
  {
    category: "Database",
    icon: "Database",
    color: "from-emerald-500 to-teal-600",
    skills: [
      { name: "PostgreSQL", level: 88 },
      { name: "MongoDB", level: 85 },
      { name: "SQL Server", level: 82 },
      { name: "MariaDB", level: 85 },
    ],
  },
  {
    category: "Realtime & Messaging",
    icon: "Zap",
    color: "from-amber-500 to-orange-600",
    skills: [
      { name: "WebSocket / Socket.IO", level: 88 },
      { name: "Kafka", level: 75 },
      { name: "Redis", level: 82 },
    ],
  },
  {
    category: "Monitoring",
    icon: "TrendingUp",
    color: "from-pink-500 to-rose-600",
    skills: [
      { name: "Prometheus", level: 78 },
      { name: "Grafana", level: 80 },
    ],
  },
  {
    category: "AI / Data",
    icon: "Brain",
    color: "from-violet-500 to-fuchsia-600",
    skills: [
      { name: "Gemini AI / AWS Bedrock", level: 85 },
      { name: "Python FastAPI", level: 82 },
      { name: "Prophet Model", level: 75 },
      { name: "Recommendation Systems", level: 80 },
      { name: "Supabase", level: 85 },
    ],
  },
];

export const PROJECTS: Project[] = [
  {
    id: "6",
    title: "HRMPro",
    description:
      "Full-stack Human Resource Management platform built to centralize employee data, automate core HR workflows, and separate staff, manager, and administrator responsibilities through role-based access control.",
    features: [
      "Modular HR domain covering employees, departments, positions, attendance, leave requests, and payroll-support workflows",
      "Role-based access control for administrators, managers, and employees with protected API routes",
      "RESTful backend architecture separating controller, service, repository, DTO, and entity layers",
      "Structured relational data model for employee records, organizational units, and HR transactions",
      "Responsive management UI for searching, filtering, updating, and maintaining HR records",
      "Validation and error-handling flow designed for reliable internal operations",
    ],
    techStack: [
      "ReactJS",
      "TailwindCSS",
      "Spring Boot",
      "REST API",
      "JWT",
      "JPA/Hibernate",
      "MySQL",
      "Docker",
      "Role-Based Access Control",
      "Layered Architecture",
    ],
    githubUrl: "https://github.com/DuongGB/HRMPro",
    liveUrl: "",
    featured: true,
  },
  {
    id: "5",
    title: "D-Sport Center",
    description:
      "Enterprise-grade sports court booking and operations platform with a React management portal, Spring Boot service layer, PostgreSQL persistence, online payment flow, QR check-in, AI booking assistance, and real-time staff notifications.",
    features: [
      "Layered full-stack architecture with React/Vite frontend, Spring Boot REST APIs, JPA repositories, DTO mapping, and PostgreSQL database",
      "Court availability engine for date-based slot selection, booking creation, payment status tracking, and staff-side reservation management",
      "PayPal Smart Checkout integration across frontend and backend with order confirmation and payment validation flow",
      "QR ticket generation and scanner-based check-in using qrcode.react and @yudiel/react-qr-scanner",
      "Real-time operational alerts through Spring WebSocket, SockJS, STOMP, and dashboard notifications",
      "AI booking assistant integrated with Gemini to guide users through court selection and booking questions",
      "Admin dashboard with TanStack Table, Recharts, Excel export, form validation, and toast/sonner feedback",
      "Database migration and repeatable environment setup using Liquibase and Docker Compose",
    ],
    techStack: [
      "React 19",
      "Spring Boot 4",
      "PostgreSQL",
      "Spring Security",
      "Liquibase",
      "SockJS/STOMP",
      "PayPal SDK",
      "TanStack Query",
      "Redux Toolkit",
      "TanStack Table",
      "React Hook Form",
      "Yup",
      "Recharts",
      "QR Scanner",
      "Cloudinary",
      "Gemini AI",
      "MapStruct",
      "Lombok",
      "Docker",
      "TailwindCSS",
      "Shadcn/ui",
    ],
    githubUrl: "https://github.com/DuongGB/sports-center",
    liveUrl: "",
    featured: true,
  },
  {
    id: "1",
    title: "Tech E-commerce Platform",
    description:
      "Full-stack technology retail platform with a React customer/admin frontend and Spring Boot backend, designed around product catalog management, secure checkout, role-based administration, media upload, AI support, and location-aware delivery features.",
    features: [
      "Product, category, inventory, cart, order, and customer-management workflows for a complete retail operation",
      "Spring Security and JWT resource-server architecture for protected APIs and role-based admin/customer access",
      "Frontend state and server-cache strategy using Redux Toolkit, TanStack Query, Axios, and React Router",
      "Payment and checkout experience using PayPal React SDK with order-status handling",
      "AI user-support flow using Google Gemini SDK and markdown rendering for guided product assistance",
      "Media and account integrations with Firebase Admin, Firebase frontend SDK, Cloudinary, and Google Drive Picker",
      "Map-based delivery/location features using Google Maps API, Leaflet, React Leaflet, and geolib",
      "Admin analytics and reporting UI with Recharts, pagination, form validation, alerts, and responsive component libraries",
    ],
    techStack: [
      "React 19",
      "Spring Boot 3",
      "MariaDB",
      "Spring Security",
      "JWT",
      "Redux Toolkit",
      "TanStack Query",
      "PayPal SDK",
      "Gemini AI",
      "Firebase",
      "Cloudinary",
      "Google Maps API",
      "Leaflet",
      "MUI",
      "Bootstrap",
      "React Hook Form",
      "Yup",
      "Recharts",
      "Framer Motion",
      "Docker",
    ],
    githubUrl: "https://github.com/tienminhtran/Project_Architectural_Software",
    liveUrl: "",
    featured: true,
  },
  {
    id: "2",
    title: "Multi-Platform Social Chat",
    description:
      "Cross-platform social messaging system connecting web and mobile clients to a Spring Boot backend, with real-time private/group conversations, media sharing, notification delivery, and cloud-based asset management.",
    features: [
      "Private chat, group chat, conversation history, and user relationship flows across web and React Native clients",
      "Real-time message delivery and online-state updates using WebSocket/Socket.IO communication",
      "Mobile-first notification flow using AWS SNS for user engagement outside the active session",
      "Media upload pipeline for avatars and chat images using Cloudinary-backed storage",
      "MongoDB document model for conversations, messages, users, and flexible social metadata",
      "Shared API contract between React web, React Native mobile, and backend services",
    ],
    techStack: [
      "Spring Boot",
      "ReactJS",
      "React Native",
      "MongoDB",
      "WebSocket",
      "Socket.IO",
      "Redux",
      "AWS SNS",
      "Cloudinary",
      "REST API",
      "Cross-Platform Architecture",
      "Real-Time Messaging",
    ],
    githubUrl: "",
    liveUrl: "",
    featured: true,
  },
  {
    id: "3",
    title: "AI-Enhanced E-commerce",
    description:
      "AI-enhanced fashion e-commerce platform combining a React customer experience, multilingual UI, real-time integrations, recommendation workflows, and machine-learning services for revenue forecasting and product personalization.",
    features: [
      "Personalized product discovery with recommendation workflows and AI-assisted shopping interactions",
      "Revenue forecasting pipeline using Prophet models exposed through a Python FastAPI service",
      "Multilingual interface using i18next and react-i18next for English/Vietnamese customer journeys",
      "Frontend data-fetching architecture with TanStack Query, Axios, debounced search, and React Router",
      "Real-time update channel using SockJS and STOMP for order or operational state changes",
      "Map, chart, upload, and carousel experiences using Leaflet, Google Charts, react-dropzone, Swiper, and Firebase",
      "Cloud deployment-oriented architecture using AWS services and containerized application components",
    ],
    techStack: [
      "React 19",
      "Spring Boot",
      "Python FastAPI",
      "Prophet",
      "PostgreSQL",
      "TanStack Query",
      "Firebase",
      "i18next",
      "SockJS/STOMP",
      "Leaflet",
      "React Dropzone",
      "Google Charts",
      "Swiper",
      "TailwindCSS",
      "Docker",
      "AWS",
      "Gemini AI",
    ],
    githubUrl: "https://github.com/DuongGB/FE_DVFashion",
    liveUrl: "",
    featured: true,
  },
  {
    id: "4",
    title: "Lab Info Management System (LIMS)",
    description:
      "Enterprise laboratory information management system developed during internship, using a microservices-oriented architecture to support patient records, lab workflows, payments, notifications, monitoring, authentication, and AI-assisted internal operations.",
    features: [
      "Microservices architecture separating patient, laboratory, payment, notification, and supporting business capabilities",
      "Event-driven communication using Kafka for asynchronous workflow coordination between services",
      "Redis caching layer for frequently accessed operational data and improved service response time",
      "Authentication and authorization flow using AWS Cognito with JWT-based service protection",
      "Real-time notification channel using Socket.IO/WebSocket patterns for operational updates",
      "Observability stack with Prometheus, Grafana, Alert Manager, and Slack alert integration",
      "Frontend/admin modules built with Next.js and Shadcn/ui over PostgreSQL and MongoDB persistence",
      "AWS Bedrock integration for AI-assisted features within laboratory or internal support workflows",
    ],
    techStack: [
      "Spring Boot",
      "Kafka",
      "Redis",
      "AWS Cognito",
      "JWT",
      "Docker",
      "Prometheus",
      "Grafana",
      "Alert Manager",
      "Slack Webhook",
      "Socket.IO",
      "PostgreSQL",
      "MongoDB",
      "Next.js",
      "Shadcn/ui",
      "AWS Bedrock",
      "Microservices",
      "Event-Driven Architecture",
    ],
    githubUrl: "",
    liveUrl: "",
    featured: true,
  },
];

export const EXPERIENCES: Experience[] = [
  {
    id: "1",
    company: "FPT Software",
    role: "Intern Java Developer",
    duration: "Sep 2025 – Nov 2025",
    startDate: "2025-09-01",
    endDate: "2025-11-01",
    responsibilities: [
      "Built microservices using Spring Boot",
      "Implemented authentication with AWS Cognito and JWT",
      "Designed event-driven architecture using Kafka",
      "Implemented caching with Redis",
      "Developed real-time notification system",
      "Integrated monitoring using Prometheus and Grafana",
    ],
    technologies: [
      "Spring Boot",
      "AWS Cognito",
      "Kafka",
      "Redis",
      "Prometheus",
      "Grafana",
      "Docker",
      "Slack",
      "Alert Manager",
      "Next.js",
      "Shadcn/ui",
      "PostgreSQL",
      "MongoDB",
      "AWS Bedrock"
    ],
  },
];

export const SERVICES: Service[] = [
  {
    id: "1",
    title: "Web Development",
    description:
      "Building performant and scalable web applications using React and Spring Boot.",
    icon: "Globe",
    features: [
      "ReactJS / NextJS",
      "Spring Boot",
      "Responsive Design",
      "JWT Auth",
    ],
  },
  {
    id: "2",
    title: "Mobile App Development",
    description:
      "Creating cross-platform mobile applications with React Native for seamless user experiences.",
    icon: "Smartphone",
    features: [
      "React Native",
      "Real-time features",
      "Native modules integration",
      "Push notifications",
    ],
  },
  {
    id: "3",
    title: "Microservices Architecture",
    description:
      "Designing and implementing independent services with event-driven communication.",
    icon: "Server",
    features: [
      "Kafka / RabbitMQ",
      "API Gateway",
      "Docker / Containerization",
      "Distributed caching",
    ],
  },
  {
    id: "4",
    title: "AI Integration",
    description:
      "Integrating machine learning models and AI services into production systems.",
    icon: "Brain",
    features: [
      "Recommendation Systems",
      "Revenue Forecasting",
      "Gemini AI / Bedrock",
      "FastAPI",
    ],
  },
];
