import type {
  Project,
  Experience,
  SkillCategory,
  Service,
  NavLink,
} from "@/types";

export const NAV_LINKS: NavLink[] = [
  { label: "Home", target: "home" },
  { label: "About", target: "about" },
  { label: "Skills", target: "skills" },
  { label: "Projects", target: "projects" },
  { label: "Experience", target: "experience" },
  { label: "Contact", target: "contact" },
];

export const CV_URL =
  "https://drive.google.com/uc?export=download&id=1jDEi9qxp3ocUe8lkMT1LT4XtFnqszqxu";
export const EMAIL = "duongnguyenqn1323@gmail.com";

export const SKILLS: SkillCategory[] = [
  {
    category: "Frontend",
    icon: "Atom",
    color: "from-cyan-500 to-blue-500",
    skills: [
      { name: "ReactJS", level: 90 },
      { name: "NextJS", level: 85 },
      { name: "React Native", level: 80 },
      { name: "TailwindCSS", level: 95 },
      { name: "Redux", level: 85 },
      { name: "Bootstrap", level: 90 },
      { name: "TypeScript", level: 80 },
      { name: "JQuery", level: 95 },
      { name: "Shadcn UI", level: 85 },
    ],
  },
  {
    category: "Backend",
    icon: "Cpu",
    color: "from-orange-500 to-red-600",
    skills: [
      { name: "Java", level: 90 },
      { name: "Spring Boot", level: 92 },
      { name: "REST API", level: 95 },
    ],
  },
  {
    category: "Tools",
    icon: "Workflow",
    color: "from-indigo-500 to-purple-600",
    skills: [
      { name: "VS code", level: 85 },
      { name: "Antigravity", level: 80 },
      { name: "Bruno", level: 90 },
      { name: "GitHub/GitLab", level: 95 },
      { name: "Postman", level: 90 },
      { name: "Jira", level: 90 },
      { name: "IntelliJ IDEA", level: 95 },
    ],
  },
  {
    category: "DevOps",
    icon: "Boxes",
    color: "from-blue-600 to-cyan-600",
    skills: [
      { name: "Docker", level: 85 },
      { name: "AWS (EC2, S3, Cognito)", level: 80 },
      { name: "Jenkins", level: 85 },
      { name: "Nginx", level: 90 },
      { name: "Render", level: 85 },
      { name: "Vercel", level: 80 },
    ],
  },
  {
    category: "Database",
    icon: "Database",
    color: "from-emerald-500 to-teal-600",
    skills: [
      { name: "PostgreSQL", level: 88 },
      { name: "MongoDB", level: 85 },
      { name: "SQL Server", level: 82 },
      { name: "MariaDB", level: 85 },
    ],
  },
  {
    category: "Realtime & Messaging",
    icon: "Zap",
    color: "from-amber-500 to-orange-600",
    skills: [
      { name: "WebSocket / Socket.IO", level: 88 },
      { name: "Kafka", level: 75 },
      { name: "Redis", level: 82 },
    ],
  },
  {
    category: "Monitoring",
    icon: "TrendingUp",
    color: "from-pink-500 to-rose-600",
    skills: [
      { name: "Prometheus", level: 78 },
      { name: "Grafana", level: 80 },
    ],
  },
  {
    category: "AI / Data",
    icon: "Brain",
    color: "from-violet-500 to-fuchsia-600",
    skills: [
      { name: "Gemini AI / AWS Bedrock", level: 85 },
      { name: "Python FastAPI", level: 82 },
      { name: "Prophet Model", level: 75 },
      { name: "Recommendation Systems", level: 80 },
      { name: "Supabase", level: 85 },
    ],
  },
];

export const PROJECTS: Project[] = [
  {
    id: "6",
    title: "Human Resource Management System",
    description:
      "Full-stack Human Resource Management platform with AI-powered analytics, automated HR workflows and role-based access across administrator, manager and employee modules. Integrates Gemini AI for intelligent report generation, workforce insights, and HR data analysis.",
    features: [
      "Integrated Gemini AI for intelligent HR report generation, workforce insight explanation, and natural-language HR data analysis",
      "Automated HR workflows and enforced role-based access across administrator, manager, and employee modules",
      "Implemented system automation with Cron jobs for recurring background tasks",
      "Configured MinIO for CV information storage and MailHog for testing email confirmations and password resets",
      "Developed robust RESTful APIs with Spring Boot using a layered architecture",
      "Implemented JWT authentication and role-based authorization to secure HR operations",
      "Designed a relational database model for employee records, organizational structure, attendance, and HR transactions",
      "Built a responsive React and TailwindCSS management UI with search, filtering, record maintenance, and form validation",
    ],
    techStack: [
      "ReactJS",
      "TailwindCSS",
      "Spring Boot",
      "REST API",
      "JWT",
      "JPA/Hibernate",
      "Gemini AI",
      "Cron Job",
      "Apache POI",
      "Playwright",
      "Flyway",
      "MySQL",
      "Docker",
    ],
    githubUrl: "https://github.com/DuongGB/HRMPro",
    liveUrl: "",
    featured: true,
  },
  {
    id: "5",
    title: "Sports Facility Booking & Operations Platform",
    description:
      "Enterprise-grade sports court booking and operations platform with online payment, QR check-in, AI booking assistance, real-time staff notifications and an admin management dashboard.",
    features: [
      "Built a full-stack booking system with React/Vite frontend, Spring Boot REST APIs, PostgreSQL persistence and JPA repositories",
      "Implemented court availability, date-based slot selection, booking creation, reservation management and payment status tracking",
      "Integrated PayPal Smart checkout with backend order confirmation and payment validation flow",
      "Developed QR ticket generation and scanner-based check-in using qrcode.react and @yudiel/react-qr-scanner",
      "Added real-time operational alerts using Spring WebSocket, SockJS, STOMP and dashboard notifications",
      "Integrated Gemini AI as a booking assistant to guide users through court selection and booking questions",
      "Deployed the backend on Render and frontend on Vercel with Docker containerization",
    ],
    techStack: [
      "React 19",
      "Spring Boot 4",
      "PostgreSQL",
      "Spring Security",
      "Liquibase",
      "SockJS/STOMP",
      "PayPal SDK",
      "Redux Toolkit",
      "TanStack Query",
      "TanStack Table",
      "Recharts",
      "Gemini AI",
      "Cloudinary",
      "Vercel",
      "Render",
      "Docker",
      "TailwindCSS",
      "Shadcn/ui",
    ],
    githubUrl: "https://github.com/DuongGB/sports-center",
    liveUrl: "",
    featured: true,
  },
  {
    id: "3",
    title: "E-commerce with AI Recommendation & Revenue Forecasting",
    description:
      "A full-stack e-commerce system based on Client-Server architecture with a clear separation between the UI and business logic, featuring AI-based recommendation and revenue forecasting.",
    features: [
      "Developed a full-stack system based on Client-Server architecture with a clear separation between the UI and business logic",
      "Built robust RESTful APIs with Spring Boot 3 (JWT, complex business logic) and a responsive, multi-language UI with ReactJS, TailwindCSS & i18next, featuring real-time chat via WebSockets",
      "Implemented a Hybrid Recommendation System and Revenue Forecasting using Python (FastAPI) and the Prophet model (Meta AI)",
      "Successfully integrated PayPal (Payment), GHN (Logistics), Cloudinary (CDN), and Firebase (Auth/OTP)",
      "Containerized with Docker; deployed Backend on AWS EC2/Render, Frontend on Vercel with CI/CD, and managed serverless data via Neon (PostgreSQL)",
    ],
    techStack: [
      "Java (Spring Boot 3)",
      "ReactJS",
      "TailwindCSS",
      "Axios",
      "React Query",
      "i18next",
      "Python (FastAPI)",
      "Prophet (Meta AI)",
      "Neon (PostgreSQL)",
      "Docker",
      "WebSocket",
      "Vercel",
      "Render",
      "AWS EC2",
    ],
    githubUrl: "https://github.com/DuongGB/FE_DVFashion",
    liveUrl: "",
    featured: true,
  },
  {
    id: "2",
    title: "Cross-Platform Real-Time Social Chat Application",
    description:
      "A cross-platform communication system using Client-Server architecture, supporting real-time interactions for both Web and Mobile.",
    features: [
      "Developed a cross-platform communication system using Client-Server architecture, supporting real-time interactions for both Web and Mobile",
      "Built private/group chats, social feeds (posts, likes, comments), friend management, and QR code integration for quick networking",
      "Implemented real-time messaging via STOMP and Socket.IO; secured the system with JWT-based authentication and Role-Based Access Control (RBAC)",
      "Integrated Cloudinary for CDN-based media delivery and optimized image processing; utilized MongoDB for flexible, high-speed message storage",
      "Developed responsive interfaces using React (Web) and React Native (Mobile), managing complex application states with Redux",
    ],
    techStack: [
      "Java (Spring Boot)",
      "ReactJS",
      "React Native",
      "MongoDB",
      "WebSocket",
      "AWS SNS",
      "Cloudinary",
      "Redux",
      "Bootstrap",
      "STOMP Protocol",
      "Gemini AI",
      "Firebase",
    ],
    githubUrl: "",
    liveUrl: "",
    featured: true,
  },
  {
    id: "1",
    title: "Full-Stack Tech E-Commerce Platform",
    description:
      "A comprehensive e-commerce solution using Client-Server architecture, tailored for high-volume tech product sales.",
    features: [
      "Developed a comprehensive e-commerce solution using Client-Server architecture, tailored for high-volume tech product sales",
      "Designed a modular Spring Boot architecture utilizing Service Layer, DTO mapping, and Repository patterns to ensure high maintainability and performance",
      "Implemented a secure authentication system using JWT and Firebase; established a granular Role-Based Access Control (RBAC) for Admin, Manager, and Customer levels",
      "Integrated Gemini AI for intelligent user support and implemented QR Code payment automation for streamlined banking transactions",
      "Containerized the entire application ecosystem using Docker for consistent development and production environments",
    ],
    techStack: [
      "ReactJS",
      "Axios",
      "Bootstrap",
      "Java (Spring Boot)",
      "JWT",
      "MariaDB",
      "Firebase",
      "Docker",
      "Gemini AI",
    ],
    githubUrl: "https://github.com/tienminhtran/Project_Architectural_Software",
    liveUrl: "",
    featured: true,
  },
  {
    id: "4",
    title: "Laboratory Information Management System (LIMS)",
    description:
      "A microservices-based Laboratory Information Management System (LIMS) platform developed during internship at FPT Software, supporting patients, test orders, and laboratory workflows.",
    features: [
      "Developed a microservices-based LIMS platform using Spring Boot 3.3 and Java 21, including IAM, Patient, Test Order, Instrument, and Warehouse services",
      "Worked in Agile/Scrum environment with Git/GitLab workflows",
      "Implemented secure authentication and authorization with AWS Cognito, JWT, OAuth2, and RBAC",
      "Built scalable event-driven workflows using Apache Kafka, with Redis caching and real-time notifications via Socket.IO",
      "Integrated payment processing, AI-powered analysis with AWS Bedrock, and dynamic reporting using JasperReports",
      "Set up monitoring and observability with Prometheus, Grafana, Slack alerts, and AWS CloudWatch",
      "Developed responsive UI features using Next.js, Tailwind CSS, and shadcn/ui",
    ],
    techStack: [
      "Java 21",
      "Spring Boot",
      "Spring Security OAuth2",
      "PostgreSQL",
      "Redis",
      "Apache Kafka",
      "AWS (Cognito, S3, OpenSearch, Bedrock, CloudWatch, WAF, Route53, Certificate Manager)",
      "Socket.IO",
      "Docker",
      "Prometheus",
      "Grafana",
      "Slack",
      "JasperReports",
      "Next.js",
      "Tailwind CSS",
      "shadcn/ui",
    ],
    githubUrl: "",
    liveUrl: "",
    featured: true,
  },
];

export const EXPERIENCES: Experience[] = [
  {
    id: "2",
    company: "Techzen Company Limited",
    role: "Fullstack Developer",
    duration: "Jan 2026 – Jun 2026",
    startDate: "2026-01-01",
    endDate: "2026-06-30",
    responsibilities: [
      "Developed an internal HR analytics system using data from multiple company systems to support employee performance and workforce analysis.",
      "Built and maintained Spring Boot APIs for data processing, Excel export/import, and employee analytics using Apache POI.",
      "Optimized API performance by improving database queries, reducing unnecessary data loading, and applying pagination and filtering for large HR datasets.",
      "Implemented data synchronization from multiple internal sources to centralize and standardize HR data.",
      "Developed frontend features with Vue.js, i18n, and Chart.js, including dashboards, data tables, filters, and employee detail screens.",
      "Worked with relational databases to query, validate, clean, and synchronize HR data.",
      "Integrated AI-assisted features to support report generation, insight explanation, and HR data analysis.",
      "Collaborated with the HR team and internal departments to clarify requirements, fix bugs, improve features, and support testing in an Agile/Scrum environment.",
    ],
    technologies: [
      "Java",
      "Spring Boot",
      "Apache POI",
      "Vue.js",
      "i18n",
      "Chart.js",
      "AI Integration",
      "Agile/Scrum",
      "Relational Database",
      "Optimized API",
      "Playwright",
    ],
  },
  {
    id: "1",
    company: "FPT Software Ho Chi Minh",
    role: "Intern Java Developer",
    duration: "Sep 2025 – Nov 2025",
    startDate: "2025-09-01",
    endDate: "2025-11-01",
    responsibilities: [
      "Developed a microservices-based Laboratory Information Management System (LIMS) platform using Spring Boot 3.3 and Java 21, including IAM, Patient, Test Order, Instrument, and Warehouse services.",
      "Worked in Agile/Scrum environment with Git/GitLab workflows.",
      "Implemented secure authentication and authorization with AWS Cognito, JWT, OAuth2, and RBAC.",
      "Built scalable event-driven workflows using Apache Kafka, with Redis caching and real-time notifications via Socket.IO.",
      "Integrated payment processing, AI-powered analysis with AWS Bedrock, and dynamic reporting using JasperReports.",
      "Set up monitoring and observability with Prometheus, Grafana, Slack alerts, and AWS CloudWatch.",
      "Developed responsive UI features using Next.js, Tailwind CSS, and shadcn/ui.",
    ],
    technologies: [
      "Java 21",
      "Spring Boot",
      "Spring Security OAuth2",
      "PostgreSQL",
      "Redis",
      "Apache Kafka",
      "AWS (Cognito, S3, OpenSearch, Bedrock, CloudWatch, WAF, Route53, Certificate Manager)",
      "Socket.IO",
      "Docker",
      "Prometheus",
      "Grafana",
      "Slack",
      "JasperReports",
      "Next.js",
      "Tailwind CSS",
      "shadcn/ui",
    ],
  },
];

export const SERVICES: Service[] = [
  {
    id: "1",
    title: "Web Development",
    description:
      "Building performant and scalable web applications using React and Spring Boot.",
    icon: "Globe",
    features: [
      "ReactJS / NextJS",
      "Spring Boot",
      "Responsive Design",
      "JWT Auth",
    ],
  },
  {
    id: "2",
    title: "Mobile App Development",
    description:
      "Creating cross-platform mobile applications with React Native for seamless user experiences.",
    icon: "Smartphone",
    features: [
      "React Native",
      "Real-time features",
      "Native modules integration",
      "Push notifications",
    ],
  },
  {
    id: "3",
    title: "Microservices Architecture",
    description:
      "Designing and implementing independent services with event-driven communication.",
    icon: "Server",
    features: [
      "Kafka / RabbitMQ",
      "API Gateway",
      "Docker / Containerization",
      "Distributed caching",
    ],
  },
  {
    id: "4",
    title: "AI Integration",
    description:
      "Integrating machine learning models and AI services into production systems.",
    icon: "Brain",
    features: [
      "Recommendation Systems",
      "Revenue Forecasting",
      "Gemini AI / Bedrock",
      "FastAPI",
    ],
  },
];
